// Gratitude micro-prompts — 30 rotating one-liners per Master Manual.
// 1-3 entries per prompt, optional photo attach (TODO in Wave 2 polish).

export const GRATITUDE_PROMPTS: string[] = [
    'One small kindness I received today…',
    'One taste I was grateful for…',
    'One face I was glad to see…',
    'One sound that landed softly…',
    'One thing my body did well today…',
    'One text or message that meant something…',
    'One place that felt like home today…',
    'One thing that made me laugh, even quietly…',
    'One small win I almost missed…',
    'One meal I actually noticed…',
    'One person I want to thank silently…',
    'One thing I have that I did not ask for…',
    'One warmth I felt today…',
    'One boundary I was grateful to hold…',
    'One easy thing I usually take for granted…',
    'One breath that felt full…',
    'One thing I forgot to worry about today…',
    'One color I loved today…',
    'One small comfort at home…',
    'One thing my past self did that I thank her for…',
    'One song that carried me today…',
    'One kindness I offered someone…',
    'One thing that grew today…',
    'One risk that turned out fine…',
    'One friend I thought of fondly…',
    'One reason my heart is still open…',
    'One quiet moment I noticed…',
    'One small window of peace…',
    'One thing that reminded me I am not alone…',
    'One reason today counted…',
];
