// Poetry prompts — 30 openers, per Master Manual. Each begins with a line
// to complete or a form to fill in. Meant to be finished in ~3 minutes.

export const POETRY_PROMPTS: string[] = [
    'Write a 4-line poem that begins, "Today I returned…"',
    'Write a short poem that ends with the word breathe.',
    'Describe the room using only the smallest details.',
    'Write a haiku about a sound you noticed today.',
    'Write a letter, in 4 lines, to your morning self.',
    'Write about the color of your calm.',
    'Write three lines about a door you did not open.',
    'Write a poem that starts, "Before I was so busy…"',
    'Write four lines about your hands.',
    'Write about the weather inside you.',
    'Write a small song for a tired heart.',
    'Write three lines about what your breath knows.',
    'Write a note to your body, three lines only.',
    'Write about a bird you did not see, only heard.',
    'Write a poem that begins, "I will not carry…"',
    'Write four lines about being enough.',
    'Write a poem about the color of tomorrow.',
    'Write a haiku about your shoulders.',
    'Write about the smallest kind thing you did today.',
    'Write a poem that ends, "…and I stayed."',
    'Write three lines to the child you were.',
    'Write about a memory that softens you.',
    'Write four lines about the wind and your worry.',
    'Write a poem that begins, "If peace were a place…"',
    'Write about the quiet after a hard day.',
    'Write three lines to your future self at bedtime.',
    'Write a poem about a river only you can see.',
    'Write about what your name means today.',
    'Write four lines about a small ordinary bloom.',
    'Write a poem that ends, "…and it is enough."',
];
