/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/firebase.native`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/PurchaseContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/PaywallModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/BreathingLeaves`; params?: Router.UnknownInputParams; } | { pathname: `/../components/BreathingCircle`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/firebase.native`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/firebase`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/PurchaseContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/PaywallModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/BreathingLeaves`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/BreathingCircle`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../lib/firebase.native${`?${string}` | `#${string}` | ''}` | `/../lib/firebase${`?${string}` | `#${string}` | ''}` | `/../contexts/PurchaseContext${`?${string}` | `#${string}` | ''}` | `/../components/PaywallModal${`?${string}` | `#${string}` | ''}` | `/../components/BreathingLeaves${`?${string}` | `#${string}` | ''}` | `/../components/BreathingCircle${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/firebase.native`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/PurchaseContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/PaywallModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/BreathingLeaves`; params?: Router.UnknownInputParams; } | { pathname: `/../components/BreathingCircle`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; };
    }
  }
}
