/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/setup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/habit-stack/selection`; params?: Router.UnknownInputParams; } | { pathname: `/habit-stack/timer`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/evening`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/midday`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/morning`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/review`; params?: Router.UnknownInputParams; } | { pathname: `/social/invite`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/setup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/habit-stack/selection`; params?: Router.UnknownOutputParams; } | { pathname: `/habit-stack/timer`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/evening`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/midday`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/morning`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/review`; params?: Router.UnknownOutputParams; } | { pathname: `/social/invite`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/onboarding/setup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/habit-stack/selection${`?${string}` | `#${string}` | ''}` | `/habit-stack/timer${`?${string}` | `#${string}` | ''}` | `/onboarding/evening${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/midday${`?${string}` | `#${string}` | ''}` | `/onboarding/morning${`?${string}` | `#${string}` | ''}` | `/onboarding/review${`?${string}` | `#${string}` | ''}` | `/social/invite${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/setup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/habit-stack/selection`; params?: Router.UnknownInputParams; } | { pathname: `/habit-stack/timer`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/evening`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/midday`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/morning`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/review`; params?: Router.UnknownInputParams; } | { pathname: `/social/invite`; params?: Router.UnknownInputParams; };
    }
  }
}
